// Inline the dev page (index.html + src/**/*.js) into single-file outputs, and keep the exporter page in sync:
//   dist/domain-clash.html   — standalone document (double-click to open)
//   dist/artifact.html       — body-content version for the Artifact publisher (no html/head/body tags)
//   tools/export.html        — regenerated with the same script list as index.html (minus ui.js)
import { readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = readFileSync(resolve(ROOT, 'index.html'), 'utf8');
const part = (name) => {
  const a = src.indexOf(`<!--BUILD:${name}-START-->`), b = src.indexOf(`<!--BUILD:${name}-END-->`);
  if (a < 0 || b < 0) throw new Error('missing marker ' + name);
  return src.slice(a + `<!--BUILD:${name}-START-->`.length, b).trim();
};
const head = part('HEAD'), body = part('BODY'), scripts = part('SCRIPTS');
const files = [...scripts.matchAll(/<script src="([^"]+)"><\/script>/g)].map(m => m[1]);
const skip = new Set((process.env.BUILD_SKIP || 'src/labs.js').split(',').filter(Boolean)); // dev-only files
let js = '';
let bytes = 0;
const missing = [];
for (const f of files) {
  if (skip.has(f)) continue;
  let code;
  try { code = readFileSync(resolve(ROOT, f), 'utf8'); } catch { missing.push(f); continue; }
  bytes += code.length;
  js += `<script>/* ${f} */\n${code.replace(/<\/script/gi, '<\\/script')}\n</script>\n`;
}
mkdirSync(resolve(ROOT, 'dist'), { recursive: true });
const standalone = `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n${head}\n</head>\n<body>\n${body}\n${js}</body>\n</html>\n`;
const artifact = `${head}\n${body}\n${js}`;
writeFileSync(resolve(ROOT, 'dist/domain-clash.html'), standalone);
writeFileSync(resolve(ROOT, 'dist/artifact.html'), artifact);
// exporter page: same scripts (relative to tools/), no ui.js, plus the muxer and the page-side exporter
const exp = files.filter(f => f !== 'src/ui.js').map(f => `<script src="../${f}"></script>`).join('\n');
writeFileSync(resolve(ROOT, 'tools/export.html'), `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Domain Clash — video exporter</title>
<style>
  body { margin: 0; background: #17111a; color: #f3ece6; font: 13px/1.45 ui-monospace, Consolas, monospace; }
  pre { margin: 12px 16px; white-space: pre-wrap; }
</style>
</head>
<body>
<!-- GENERATED by tools/build.mjs from index.html — do not edit. Driven headlessly by tools/export.mjs. src/main.js boots
     into player mode on DOMContentLoaded and wants a #screen canvas and a #loadbar; they are provided here, hidden. -->
<div hidden><canvas id="screen" width="640" height="360"></canvas><i id="loadbar"></i></div>
<pre id="log">exporter page — waiting for tools/export.mjs</pre>
${exp}
<script src="mp4mux.js"></script>
<script src="export.js"></script>
</body>
</html>
`);
const kb = p => (statSync(resolve(ROOT, p)).size / 1024).toFixed(1) + ' KB';
console.log('scripts:', files.length - skip.size, 'inlined,', missing.length ? 'MISSING: ' + missing.join(', ') : 'none missing', skip.size ? '(skipped dev-only: ' + [...skip].join(', ') + ')' : '');
console.log('dist/domain-clash.html', kb('dist/domain-clash.html'));
console.log('dist/artifact.html', kb('dist/artifact.html'));
console.log('tools/export.html regenerated (' + (files.length - 1) + ' scripts)');
const ext = [...artifact.matchAll(/(?:src|href)="(https?:[^"]+)"/g)].map(m => m[1]);
console.log('external refs:', ext.length ? ext.join(' ') : 'none');
if (missing.length) process.exitCode = 1;
